main: com.shaewest.wareffects.App
name: wareffects
version: 1
api-version: 1.20.1
description: A plugin to add additional war based weapons and effects

commands:
  commandName:
    description: description
    usage: /command {var} {var}