main: com.shaewest.wareffects.App
name: wareffects
version: 1
api-version: 1.20
description: A plugin to add additional war based weapons and effects

commands:
  regionalweapons:
    description: Get access to war weapons like nukes.
    usage: /regionalweapons {type}